// <auto-generated />
namespace TrashCollector2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class undidnullabletypesonactualPickupandAddresstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(undidnullabletypesonactualPickupandAddresstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703302224326_undid nullable types on actual Pick up and Address table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
